var readData = require('./readData');
var crypto = require('crypto');

module.exports = async function(cookieToken, userID) {

/** 
* @summary Updates the stored accessToken for the given user
* @param {string} cookieToken - The user's accessToken, a JWT generated by pwa-auth Microsoft login
* @return {Boolean} True
*/
    

    if ((typeof cookieToken !== "string") || (typeof userID !== "number")) {
        console.log('incorrect types when updating token');
        return false          
    } else {

        var hash = crypto.createHash('md5').update(cookieToken).digest("hex");

        var updateTokenTable = "INSERT IGNORE INTO accesstokens VALUES (?, ?, ?)";
        var updateTokenTableValues = [hash, userID, cookieToken];
        var updateResults = await readData(updateTokenTable, updateTokenTableValues)
        .then(function(results) {
        })

        return true

        
    }
    
}